### PR TITLE
Verb aliases

### LINKED ISSUE #6: Verb aliases
<a href="https://github.com/kirillkovalenko"></img></a> **Issue by [kirillkovalenko](https://github.com/kirillkovalenko)**
_Tuesday Aug 20, 2013 at 17:19 GMT_
_Originally opened as https://github.com/gsscoder/commandline/issues/90_

----

I suggest implementing verb aliases. For example: hg rename, hg move, hg mv is the same command.

### LINKED ISSUE #517: Improvement: short form for verbs
We need to have some way to specify short version of the verb string, like

[Verb("inventory", alias="inv" HelpText="Show the Inventory")]
class ....

### PR DESCRIPTION
**Pull request by johnjaylward**
Fixes #6 
Fixes #517

### CODE REVIEW

**Comment by johnjaylward** [comment]
I wasn't sure how best to update the Help messages generated to indicate the new alias support. If anyone has suggestions for what they'd like to see and I can update

**Comment by moh-hassan** [comment]
Update helptext [here](
https://github.com/commandlineparser/commandline/blob/master/src/CommandLine/Text/HelpText.cs#L849)
Just add ' alias names

**Comment by moh-hassan** [comment]
Thanks for your work and fixing  #6

**Comment by johnjaylward** [comment]
Help messages updated and tested. Let me know if you think any changes are needed.

**Review by moh-hassan — APPROVED** [review]

**Comment by moh-hassan** [comment]
@johnjaylward
Please, rebase PR to develop branch and resolve confliction.
Also, for verb [test case](https://github.com/commandlineparser/commandline/pull/636/files#diff-df560a953a1e9a2a5e2fdd8847d48805R122), set `isDefault: false` or remove this line. IsDefault means don't pass verb in the commandline.

**Comment by johnjaylward** [comment]
@moh-hassan , I finished the rebase, but I don't think I need to remove the "Default Verb" setting. I set up the test case purposefully to take into account a default verb. If I remove that option, I will need to adjust my test cases accordingly.

**Comment by johnjaylward** [comment]
@moh-hassan , I ended up making a few more test cases which show that it work both with a default verb and without a default verb. Also added a few comments to show intention of the tests.

**Comment by twaalewijn** [comment]
@moh-hassan I'm working on a PR to introduce sub verbs into the library.
After I rebased/merged that work onto the latest develop several of my tests with help output started failing because certain lines we're being indented/padded differently than before.

Changing the call to `OptionSpecification.NewSwitch` that was changed in `HelpText` in this PR to once again pass `string.Empty` as the short name and concatenating the name and aliases into the long name seems to fix it.

E.g. something like this
```csharp
OptionSpecification.NewSwitch(
    string.Empty,
    new[] { verbTuple.Item1.Name }.Concat(verbTuple.Item1.Aliases).ToDelimitedString(", "),
    false,
    verbTuple.Item1.IsDefault ? "(Default Verb) " + verbTuple.Item1.HelpText : verbTuple.Item1.HelpText,  //Default verb
    string.Empty,
    verbTuple.Item1.Hidden);
```

Just thought I'd mention it before 2.9 is released in case it is a problem.

**Comment by moh-hassan** [comment]
@twaalewijn
I couldn't find `OptionSpecification.NewSwitch` in the commits of this PR.
Can you point me to the location of this change in the [commits ](https://github.com/commandlineparser/commandline/pull/636/files) of PR?

> several of my tests with help output started failing because certain lines we're being indented/padded differently than before.

Can this may to related to the Configuration of Git to handle line endings?

Can Your suggestion cause some tests to fail?

**Comment by twaalewijn** [comment]
@moh-hassan 
This is the call I am referring to: https://github.com/commandlineparser/commandline/pull/636/files#diff-88c7f4706542a25c9d5ec8b7a7b49bd5R853

As can be seen in the diff the first parameter (short name) used to be  `string.Empty` and the  verb name was passed as the second parameter (long name).

After passing both the verb name and possible aliases to the long name parameter as shown in my earlier example my expected help text was indented/aligned like it was before this PR.

> Can this may to related to the Configuration of Git to handle line endings?

I guess I cannot 100% rule that out but I do not think so.
Sorry if I did not explain it clearly enough, I'm talking about the spacing in the help that is added between the verb and help text:

`help  <this added space>  Display more information on a specific command.`

> Can Your suggestion cause some tests to fail?

It will cause these instances of theory tests to fail:
- [Issue6Tests.cs - Line 88](https://github.com/commandlineparser/commandline/pull/636/files#diff-df560a953a1e9a2a5e2fdd8847d48805R88)
- [Issue6Tests.cs - Line 96](https://github.com/commandlineparser/commandline/pull/636/files#diff-df560a953a1e9a2a5e2fdd8847d48805R96)
- [Issue6Tests.cs - Line 163](https://github.com/commandlineparser/commandline/pull/636/files#diff-df560a953a1e9a2a5e2fdd8847d48805R163)
- [Issue6Tests.cs - Line 170](https://github.com/commandlineparser/commandline/pull/636/files#diff-df560a953a1e9a2a5e2fdd8847d48805R170)

But these tests are expecting wrong outputs I think.

It isn't very easy to see in the InlineData of lines 163 and 170 but in the data of lines 88 and 96 you can see that the help text for `delete`, `help` and `version` are not lining up correctly with `copy, cp, cpy`.

The data of line 88 for example currently looks like this:
```csharp
[InlineData("--help", true, new string[]
    {
        "copy, cp, cpy    (Default Verb) Copy some stuff",
        "move, mv",
        "delete        Delete stuff",
        "help          Display more information on a specific command.",
        "version       Display version information.",
    })]
```
But should have looked like this instead:
```csharp
[InlineData("--help", true, new string[]
    {
        "copy, cp, cpy    (Default Verb) Copy some stuff",
        "move, mv",
        "delete           Delete stuff",
        "help             Display more information on a specific command.",
        "version          Display version information.",
    })]
```

**Comment by johnjaylward** [comment]
@twaalewijn, I see. The reason I swapped the verb to the "short" position was to ensure it would always be first in the list. When the verb was in the "long" position, it changed the order to have all the aliases first, which I did not like.

The `Issue6Tests` were generated for this PR. I'll look at opening a new PR to switch the order back, but that will likely change the help to read like this:
```c#
[InlineData("--help", true, new string[]
    {
        "cp, cpy, copy    (Default Verb) Copy some stuff",
        "mv, move",
        "delete           Delete stuff",
        "help             Display more information on a specific command.",
        "version          Display version information.",
    })]
```

**Pull request merged**
