### PR TITLE
Fix usage attribute error

### PR DESCRIPTION
**Pull request by lmmarsano**
Invalid Cast Exceptions were getting thrown when looking up command usages in a project compiled with C♯ 8.0.
I found code attempting to cast all attributes to the same type.
([C♯ 8.0 implicitly annotates `NullableAttribute` everywhere](https://github.com/dotnet/roslyn/blob/master/docs/features/nullable-reference-types.md#annotations) and that was getting illegally cast to `UsageAttribute`.)
These lines fix the issue.
https://github.com/commandlineparser/commandline/blob/3bffb7aa65f55011016405e5776294fa6043b620/src/CommandLine/Core/ReflectionExtensions.cs#L43-L44

We can skip the commits replacing the signing key: I had to do that to compile, though it's puzzling that .NET Core rejected the file as invalid.

While diving into the code (just to understand it before encountering the problem) I noticed similar casts over collections that weren't filtered to ensure success.
You might want to fix those.

Can you please look these over and let me know what to do?
Thanks.

### CODE REVIEW

**Comment by lmmarsano** [comment]
This same branch is passing in [my AppVeyor instance](https://ci.appveyor.com/project/lmmarsano/commandline), so the failure here is perplexing.

**Comment by alexander-87** [comment]
I believe this proposed fix would also resolve issue #136.

**Comment by moh-hassan** [comment]
@lmmarsano 
Can you try to check if the issue is still exist in v2.5 by re-building the project in vs2019 RTM, and modifying the csproj file to use c#8 by adding these two lines:

		<LangVersion>8.0</LangVersion>
		<NullableContextOptions>enable</NullableContextOptions>

**Comment by vitaliy-orlov** [comment]
I hope this fix will be merged soon. I really need it.

**Comment by bert2** [comment]
Running into the same issue. Is there a work-around for the meantime?

**Comment by moh-hassan** [comment]
@bert2
Can you provide sample project as an attach to repro the issue.

**Comment by bert2** [comment]
Sure!

```powershell
PS> git clone https://github.com/bert2/mediocre.git # clone the repro project
...
PS> cd .\mediocre\
PS> git checkout 425-repro # checkout the commit/tag that reproduces the issue
...
PS> dotnet run -p .\mediocre -- help list # run the project and show the help for the `list` verb
Unhandled exception. System.InvalidCastException: Unable to cast object of type 'System.Runtime.CompilerServices.NullableAttribute' to type 'CommandLine.Text.UsageAttribute'.
   at CommandLine.Core.ReflectionExtensions.<>c.<GetUsageData>b__2_3(<>f__AnonymousType1`2 <>h__TransparentIdentifier0)
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.SingleOrDefault[TSource](IEnumerable`1 source)
   at CommandLine.Core.ReflectionExtensions.GetUsageData(Type type)
   at CommandLine.Text.HelpText.GetUsageFromType(Type type)
   at CommandLine.Text.HelpText.RenderUsageTextAsLines[T](ParserResult`1 parserResult, Func`2 mapperFunc)+MoveNext()
   at CSharpx.EnumerableExtensions.ToMaybe[T](IEnumerable`1 source)
   at CommandLine.Text.HelpText.AutoBuild[T](ParserResult`1 parserResult, Func`2 onError, Func`2 onExample, Boolean verbsIndex, Int32 maxDisplayWidth)
   at CommandLine.Text.HelpText.AutoBuild[T](ParserResult`1 parserResult, Func`2 onError, Int32 maxDisplayWidth)
   at Mediocre.Program.ShowHelp(NotParsed`1 result) in D:\DEV\test\mediocre\mediocre\Program.cs:line 110
   at Mediocre.Program.<>c__DisplayClass7_0.<MapResult>b__0(IEnumerable`1 _) in D:\DEV\test\mediocre\mediocre\Program.cs:line 131
   at CommandLine.ParserResultExtensions.MapResult[T1,T2,T3,T4,TResult](ParserResult`1 result, Func`2 parsedFunc1, Func`2 parsedFunc2, Func`2 parsedFunc3, Func`2 parsedFunc4, Func`2 notParsedFunc)
   at Mediocre.Program.MapResult(ParserResult`1 result, Func`2 parsedSync, Func`2 parsedPrint, Func`2 parsedRead, Func`2 parsedList, Func`2 notParsed) in D:\DEV\test\mediocre\mediocre\Program.cs:line 126
   at Mediocre.Program.Main(String[] args) in D:\DEV\test\mediocre\mediocre\Program.cs:line 14
   at Mediocre.Program.<Main>(String[] args)
PS> notepad .\mediocre\cli\ListOpts.cs # fix the `list` verb by removing the property `ListOpts.Examples`
PS> dotnet run -p .\mediocre -- help list # try again
mediocre 1.0.0

  --filter=STRING       Optional filter. Only list items with STRING in their
                        name.
  --help                Display this help screen.
  --version             Display version information.
  what (pos. 0) ENUM    Required. What should be listed. Valid values: devices,
                        screens
```

This is the content of `ListOpts.cs`:

```csharp
namespace Mediocre.Prototype {
    using System.Collections.Generic;

    using CommandLine;
    using CommandLine.Text;

    [Verb("list")]
    public readonly struct ListOpts {
        [Value(0,
            Required = true,
            MetaName = "what",
            MetaValue = "ENUM",
            HelpText = "What should be listed.")]
        public ListType What { get; }

        [Option(
            Default = null,
            MetaValue = "STRING",
            HelpText = "Optional filter. Only list items with STRING in their name.")]
        public string? Filter { get; }

        public ListOpts(ListType what, string? filter) {
            What = what;
            Filter = filter;
        }

        [Usage(ApplicationAlias = "yourapp")]
        public static IEnumerable<Example> Examples {
            get {
                yield return new Example("Normal scenario", new ListOpts(ListType.screens, null));
            }
        }
    }

    public enum ListType {
        devices,
        screens
    }
}
```

As you can see `ListOpts` is a `readonly struct`. I also tried making it a `class`, but that didn't help.

Is this sufficient? Let me know if you need anything else.

**Comment by moh-hassan** [comment]
Thanks @bert2  for the demo.
Your demo help to repro the issue.
The root problem is any nullable property (e.g string? name)  in the class /struct is the source of this issue.
Without nullable properties, it's fine see  [online demo](https://dotnetfiddle.net/91uSxG).
I can repro the issue in this [the same online demo](https://dotnetfiddle.net/91uSxG) by commenting/uncomment line 93,94.
I'll try merge this PR and test your case and feedback.

**Comment by bert2** [comment]
That's great news. Thanks for looking into it @moh-hassan!

**Comment by moh-hassan** [comment]
Merged manually after rebasing to develop and resolving confliction at commit [074d0507](https://github.com/commandlineparser/commandline/commit/074d050701f6ede065151fe4b68da497dae74df1) with build success on [Appveyor](https://ci.appveyor.com/project/commandlineparser/commandline/builds/34730535)

**Comment by moh-hassan** [comment]
@bert2 
Please, can you try the feature using the nuget package on [Appveyor server: 2.9.0-ci-190](https://ci.appveyor.com/api/buildjobs/41bqyr2j14tqfki7/artifacts/src%2FCommandLine%2Fbin%2FRelease%2FCommandLineParser.2.9.0-ci-190.nupkg).
I test your project using this package `v 2.9.0-ci-190` and it's working fine.
The help screen for the command:
`dotnet run -p .\mediocre -- help list `
```
Normal scenario:
  yourapp list --filter xyz screens

  --filter=STRING       Optional filter. Only list items with STRING in their
                        name.
  --help                Display this help screen.
  --version             Display version information.
  what (pos. 0) ENUM    Required. What should be listed. Valid values: devices,
                        screens

```

**Comment by bert2** [comment]
@moh-hassan Works perfectly with 2.9.0! Thanks!

**Comment by moh-hassan** [comment]
@bert2 
Thanks for feedback.

**Comment by bert2** [comment]
Hey @moh-hassan, is it possible to release this fix in a new preview version?

**Comment by moh-hassan** [comment]
@bert2 
The fix can be added  in the release v2.9.0

**Comment by moh-hassan** [comment]
@ericnewton76 
@gsscoder

**Comment by moh-hassan** [comment]
Hi @bert2
```
 is it possible to release this fix in a new preview version?
```
I can't publish a new version because the nuget key expired and waiting the project owner to renew the key.

**Pull request closed without merging**
