### PR TITLE
Proposed changes for enhancement:

### PR DESCRIPTION
**Pull request by Wind010**
https://github.com/commandlineparser/commandline/issues/189

### CODE REVIEW

**Review by ericnewton76 — COMMENTED** [review]
I might roll back some of the CSPROJ reference changes made here...

We switched to being a NetCore library now.

**Comment by Wind010** [comment]
Sounds good to me.

**Comment by Wind010** [comment]
Should I just pull latest into my fork and resolve the conflicts?

**Comment by ericnewton76** [comment]
That would be easiest for me... when I'm merging, it's hard to discern your code from somebody else's   

When you are merging its much easier to discern your code from somebody else's  ;-)

^ ^ ^ ^
Yeah, when you first read it, its weird and then it makes sense... lol

**Comment by Wind010** [comment]
I've merged down to my fork and resolved the conflicts.  Basically took everything from upstream and just kept my changes.

**Comment by ericnewton76** [comment]
Looks like there was a csproj merge issue in the appveyor build

**Comment by Wind010** [comment]
Build fixed locally, updating tests.

**Comment by Wind010** [comment]
Please review latest changes.

**Comment by twaalewijn** [comment]
@Wind010 Excuse me for asking and perhaps I am missing something but could it be that your merge commit already accidentally ended up in the main repository?

I did a fresh fork a couple of days ago and building the develop/master branches gives me errors that would have been fixed by your latest commit.

**Comment by Wind010** [comment]
@twaalewijn Yeah, it looks like the initial PR changes were merged into the main repository:
https://github.com/commandlineparser/commandline/commit/bd67c24b6b8e91393466b3b86207e1418f249826

I've merged merged upstream master into my fork's master and resolved the breaks.  All tests are successful in the latest changes in this PR.

**Comment by Wind010** [comment]
@ericnewton76 Should I close this PR and open one where I merge from my fork master to the upstream master?

**Comment by ericnewton76** [comment]
thats odd, seems like it should still pickup your changes. 

Did you check into your Wind010/master branch?

**Comment by Wind010** [comment]
Sorry for the late reply.  Yes, master should have the latest changes with the conflicts resolved.

https://github.com/Wind010/commandline/commits/master

The broken commit was made on the 24th, it looks like the merge of my fork to main fork was done on the 27th, but the fix/proper resolve was done on the 29th.

**Comment by ebjornset** [comment]
@Wind010, @ericnewton76  I just forked commandline, and it seems to me that this PR is not merged in yet? At least I get compilation errors for the issues this PR seems to fix.

**Comment by moh-hassan** [comment]
@ebjornset 
Yes, You are correct.
There is a compilation error in the commit 030eb8d on Feb 1.
Last merge need to be corrected.

@Wind010, @ericnewton76
It seems that last merge cause a compilation error and need to be fixed.
I had to stop rebasing my [PR ](https://github.com/commandlineparser/commandline/pull/387)with the upstream

**Comment by Wind010** [comment]
I'll open up a fresh PR to merge from commandlineparser:develop from wind010:master.

**Pull request closed without merging**
