### PR TITLE
Update project links in nuget package spec

### PR DESCRIPTION
**Pull request by nemec**
Project moved to a new organization, updating links to match.

### CODE REVIEW

**Comment by nemec** [comment]
Sending a pull request as I don't have write access to the repo right now

**Comment by ericnewton76** [comment]
Great first pull request! Thanks.  

I'll check into the write access issue.  Realistically we should consider not allowing direct write access to master/release branches except for pull requests.  This is so that any leaders of the project have a chance to comment on any pull request before its merged.  

Its actually even more rewarding because everybody sees that leaders live by the same rules as everybody else... ;-)

Does that sound reasonable?

**Comment by ericnewton76** [comment]
Ah, I had invited you but it doesnt automatically give you owner status.  Makes sense... and fixed.

**Comment by nemec** [comment]
That's a great idea. It never hurts to have someone double check your work.

**Pull request merged**
