### PR TITLE
Add support for TimeSpan

### PR DESCRIPTION
**Pull request by 0xced**
This is a work in progress, please do not merge yet.

### CODE REVIEW

**Comment by 0xced** [comment]
It looks fine now. You can merge if you think this is a good addition.

**Comment by 0xced** [comment]
Oh and by the way, I found why 30 tests were failing: because `Console.WindowWidth` returns `0` when running under mono leading to `ArgumentOutOfRangeException` being thrown because [maximumLength < 1](https://github.com/commandlineparser/commandline/blob/f68a93f97c959697fa134222dca6344d2ebfac5f/src/CommandLine/Text/HelpText.cs#L634-L637).

**Comment by nemec** [comment]
This is great - not only will it work for TimeSpans, but any class with a TypeConverter should be supported by the library now.

Thank you for contributing, @0xced!

**Comment by ericnewton76** [comment]
@0xced hey cedric, regarding the tests and the maximumLength, you are exactly right.  I was trying to find some time to implement that aspect in the testing apparatus to force that variable to always be 80 instead of -1 if the Console.WindowWidth access failed.  You'll probably see a pull request from me regarding that at some point

**Comment by 0xced** [comment]
I noticed that this pull request was merged (into develop) but only commit 6e52805a11a455396581b7b3d8a168ec1c6e1ff3 was cherry-picked for version 2.2.1. Are you going to merge it in into master for the next release?

**Pull request merged**
