### PR TITLE
Fix not showing correct header info, issue #34

### PR DESCRIPTION
**Pull request by tynar**
Added preprocessor for .NET Standard and .NET Framework to fix HeadingInfo issue #34 .

### CODE REVIEW

**Comment by nemec** [comment]
I'm beginning to think a better solution may be to simply remove `.dll` from the end of the title if it exists. It won't require adding new preprocessors and will only affect those who intentionally end their title with `.dll`, for whatever reason, instead of all of NETSTANDARD.

@tynar I don't see a preprocessor for .NET Framework that calls `Path.GetFileNameWithoutExtension`, it would hit your `#else` and simply not trim. Since that trim call was added back in 2013, before Core even existed, .NET Framework users should get the behavior that trims `.dll` off the end as well as netstandard1_5.

Could you rewrite your change to remove just the string `.dll` from the end of the title, if it exists? If it passes the tests after that, we should be good to go.

**Comment by tynar** [comment]
Wasn't the intention to show the title from AssemblyInfo rather than looking for executed file name? That's why I left else part with title info which is available in .NET Framework.

**Comment by nemec** [comment]
Yes. Note that the existing code calls `GetFileNameWithoutExtension` on the title attribute, NOT the assembly name. I believe it's meant to solve a problem where, by default, the title attribute is given a name of `something.dll` if you did not manually set it yourself.

I think if you take the current published code and then replace

    GetFileNameWithoutExtension(titleAttribute.Title)

 with the following pseudocode (sorry I don't have the time to format it properly)

    title = titleAttribute.Title
    if title endswith ".dll"
        title = title.Substring(0, title.Length - ".dll".Length)

It should solve the original issue while keeping the spirit of the old behavior.

**Comment by nemec** [comment]
That looks good to me @tynar, thank you for your contribution to the project!

**Pull request merged**
